openapi: "3.0.3"
info:
  title: "Keran Fidelity System - Loyalty Card update API"
  description: "This API is used to update loyalty Cards"
  version: "1.0.0"
servers:
  - url: "https://keran_fidelity_system_service/api/v1"
paths:
  /api/v1/loyaltyCard/{loyaltyCardId}:
    put:
      tags:
        - LoyaltyCardUpdateController
      summary: "Update loyalty Card."
      operationId: "updateLoyaltyCard"
      description: "Updates a specific loyalty Card"
      parameters:
        - name: "loyaltyCardId"
          in: "path"
          description: "Existing database ID of a loyalty Card"
          required: true
          schema:
            type: "string"
            format: "uuid"
            example: "8d2f54d8-6ee7-4e20-854d-7fccc9b477b4"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../model/swagger-loyaltyCard.yaml#/components/schemas/loyaltyCardApiObject'
      responses:
        "200":
          description: "OK - loyalty Card created successfully"
          content:
            application/json:
              schema:
                $ref: '../model/swagger-loyaltyCard-api-response-object.yaml#/components/schemas/loyaltyCardResponseObject'
        "404":
          description: "NOT FOUND - loyalty customer could not be found"
          content:
            application/json:
              schema:
                $ref: '../../common/swagger-common-api-error-response-object.yaml#/components/schemas/commonApiErrorResponseObject'