openapi: "3.0.3"
info:
  title: "Keran Fidelity System - Loyalty Card add API"
  description: "This API is used to add loyalty Cards to the database"
  version: "1.0.0"
servers:
  - url: "https://keran_fidelity_system_service/api/v1"
paths:
  /api/v1/loyaltyCard/{loyaltyCustomerId}:
    post:
      tags:
        - LoyaltyCardAddController
      summary: "Add loyalty Card."
      operationId: "addLoyaltyCardById"
      description: "Adds a specific loyalty Card to a specific loyalty customer"
      parameters:
        - name: "loyaltyCustomerId"
          in: "path"
          description: "Existing database ID of a loyalty customer"
          required: true
          schema:
            type: "string"
            format: "uuid"
            example: "8d2f54d8-6ee7-4e20-854d-7fccc9b477b4"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../model/swagger-loyaltyCard.yaml#/components/schemas/loyaltyCardApiObject'
      responses:
        "200":
          description: "OK - loyalty Card created successfully"
          content:
            application/json:
              schema:
                $ref: '../model/swagger-loyaltyCard-api-response-object.yaml#/components/schemas/loyaltyCardResponseObject'
        "404":
          description: "NOT FOUND - loyalty customer could not be found"
          content:
            application/json:
              schema:
                $ref: '../../common/swagger-common-api-error-response-object.yaml#/components/schemas/commonApiErrorResponseObject'