spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/keran_db}
    password: ${DB_PASSWORD:admin}
    username: ${DB_USER_NAME:admin}
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: '20000'
      maximumPoolSize: '5'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never

kafka:
  bootstrap:
    servers: localhost:8670