openapi: "3.0.3"
info:
  title: "Keran Fidelity System - find API"
  description: "This API is used to find loyalty EventOccurrences from the database"
  version: "1.0.0"
servers:
  - url: "https://keran_fidelity_system_service/api/v1"
paths:
  /api/v1/loyaltyEventOccurrence/{loyaltyEventOccurrenceId}:
    get:
      tags:
        - LoyaltyEventOccurrenceFindController
      summary: "Find loyalty EventOccurrence by ID."
      operationId: "findLoyaltyEventOccurrenceById"
      description: "Finds a specific loyalty EventOccurrence by its database ID"
      parameters:
        - name: "loyaltyEventOccurrenceId"
          in: "path"
          description: "Existing database ID of a loyalty EventOccurrence"
          required: true
          schema:
            type: "string"
            format: "uuid"
            example: "8d2f54d8-6ee7-4e20-854d-7fccc9b477b4"
      responses:
        "200":
          description: "OK - loyalty EventOccurrence found successfully"
          content:
            application/json:
              schema:
                $ref: '../model/swagger-loyaltyEventOccurrence-api-response-object.yaml#/components/schemas/loyaltyEventOccurrenceResponseObject'
        "404":
          description: "NOT FOUND - loyalty EventOccurrence could not be found"
          content:
            application/json:
              schema:
                $ref: '../../common/swagger-common-api-error-response-object.yaml#/components/schemas/commonApiErrorResponseObject'