openapi: "3.0.3"
info:
  title: "Keran Fidelity System - add API"
  description: "This API is used to add loyalty EventOccurrences to the database"
  version: "1.0.0"
servers:
  - url: "https://keran_fidelity_system_service/api/v1"
paths:
  /api/v1/loyaltyEventOccurrence/{loyaltyCustomerId}/{loyaltyEventId}:
    post:
      tags:
        - LoyaltyEventOccurrenceAddController
      summary: "Add loyalty EventOccurrence."
      operationId: "addLoyaltyEventOccurrenceById"
      description: "Adds a specific loyalty EventOccurrence to a specific loyalty account"
      parameters:
        - name: "loyaltyCustomerId"
          in: "path"
          description: "Existing database ID of a loyalty customer"
          required: true
          schema:
            type: "string"
            format: "uuid"
            example: "8d2f54d8-6ee7-4e20-854d-7fccc9b477b4"
        - name: "loyaltyEventId"
          in: "path"
          description: "Existing database ID of a loyalty event"
          required: true
          schema:
            type: "string"
            format: "uuid"
            example: "8d2f54d8-6ee7-4e20-854d-7fccc9b477b4"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../model/swagger-loyaltyEventOccurrence.yaml#/components/schemas/loyaltyEventOccurrenceApiObject'
      responses:
        "200":
          description: "OK - loyalty EventOccurrence created successfully"
          content:
            application/json:
              schema:
                $ref: '../model/swagger-loyaltyEventOccurrence-api-response-object.yaml#/components/schemas/loyaltyEventOccurrenceResponseObject'
        "404":
          description: "NOT FOUND - loyalty customer could not be found"
          content:
            application/json:
              schema:
                $ref: '../../common/swagger-common-api-error-response-object.yaml#/components/schemas/commonApiErrorResponseObject'