openapi: "3.0.3"
info:
  title: "Keran Fidelity System - find API"
  description: "This API is used to find loyalty PointBalances from the database"
  version: "1.0.0"
servers:
  - url: "https://keran_fidelity_system_service/api/v1"
paths:
  /api/v1/loyaltyPointBalance/{loyaltyPointBalanceId}:
    get:
      tags:
        - LoyaltyPointBalanceFindController
      summary: "Find loyalty PointBalance by ID."
      operationId: "findLoyaltyPointBalanceById"
      description: "Finds a specific loyalty PointBalance by its database ID"
      parameters:
        - name: "loyaltyPointBalanceId"
          in: "path"
          description: "Existing database ID of a loyalty PointBalance"
          required: true
          schema:
            type: "string"
            format: "uuid"
            example: "8d2f54d8-6ee7-4e20-854d-7fccc9b477b4"
      responses:
        "200":
          description: "OK - loyalty PointBalance found successfully"
          content:
            application/json:
              schema:
                $ref: '../model/swagger-loyaltyPointBalance-api-response-object.yaml#/components/schemas/loyaltyPointBalanceResponseObject'
        "404":
          description: "NOT FOUND - loyalty PointBalance could not be found"
          content:
            application/json:
              schema:
                $ref: '../../common/swagger-common-api-error-response-object.yaml#/components/schemas/commonApiErrorResponseObject'