components:
  schemas:
    loyaltyCardApiObject:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        loyaltyCustomerId:
          type: "string"
          format: "uuid"
        cardNumber:
          type: "string"
        displayName:
          type: "string"
        cardImageUrl:
          type: "string"
        lastModificationOn:
          type: "string"
          format: "date"
        lastModificationBy:
          type: "string"
