components:
  schemas:
    loyaltyCardApiObject:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        loyaltyCustomerId:
          type: "string"
          format: "uuid"
        cardNumber:
          type: "string"
        displayName:
          type: "string"
        cardImageUrl:
          type: "string"
        cardType:
          type: "string"
          enum:
            - "L1_STANDARD"
            - "L2_PREMIUM"
            - "L3_VIP"
        lastModificationOn:
          type: "string"
          format: "date"
        lastModificationBy:
          type: "string"
