components:
  schemas:
    loyaltyCardResponseObject:
      type: "object"
      properties:
        common:
          $ref: "../../common/swagger-common.yaml#/components/schemas/common"
        loyaltyCardApiObjects:
          type: "array"
          items:
            $ref: "swagger-loyaltyCard.yaml#/components/schemas/loyaltyCardApiObject"