components:
  schemas:
    common:
      type: "object"
      properties:
        responseCode:
          type: "HttpStatus"
        message:
          type: "string"
        wasSuccess:
          type: "boolean"
        timestamp:
          type: "string"
          format: "date"
        exception:
          type: "RuntimeException"
          required: false