openapi: "3.0.3"
info:
  title: "Keran Fidelity System - update API"
  description: "This API is used to update loyalty Events"
  version: "1.0.0"
servers:
  - url: "https://keran_fidelity_system_service/api/v1"
paths:
  /api/v1/loyaltyEvent/{loyaltyEventId}:
    put:
      tags:
        - LoyaltyEventUpdateController
      summary: "Update loyalty Event."
      operationId: "updateLoyaltyEvent"
      description: "Updates a specific loyalty Event"
      parameters:
        - name: "loyaltyEventId"
          in: "path"
          description: "Existing database ID of a loyalty Event"
          required: true
          schema:
            type: "string"
            format: "uuid"
            example: "8d2f54d8-6ee7-4e20-854d-7fccc9b477b4"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../model/swagger-loyaltyEvent.yaml#/components/schemas/loyaltyEventApiObject'
      responses:
        "200":
          description: "OK - loyalty Event created successfully"
          content:
            application/json:
              schema:
                $ref: '../model/swagger-loyaltyEvent-api-response-object.yaml#/components/schemas/loyaltyEventResponseObject'
        "404":
          description: "NOT FOUND - loyalty customer could not be found"
          content:
            application/json:
              schema:
                $ref: '../../common/swagger-common-api-error-response-object.yaml#/components/schemas/commonApiErrorResponseObject'