openapi: "3.0.3"
info:
  title: "Keran Fidelity System - delete API"
  description: "This API is used to remove loyalty Events from the database"
  version: "1.0.0"
servers:
  - url: "https://keran_fidelity_system_service/api/v1"
paths:
  /api/v1/loyaltyEvent/{loyaltyEventId}:
    delete:
      tags:
        - loyaltyEventDeleteController
      summary: "Delete loyalty Event by ID."
      operationId: "deleteLoyaltyEventById"
      description: "Deletes a specific loyalty Event by its database ID"
      parameters:
        - name: "loyaltyEventId"
          in: "path"
          description: "Existing database ID of a loyalty Event"
          required: true
          schema:
            type: "string"
            format: "uuid"
            example: "8d2f54d8-6ee7-4e20-854d-7fccc9b477b4"
      responses:
        "200":
          description: "OK - loyalty Event deleted successfully"
          content:
            application/json:
              schema:
                $ref: '../model/swagger-loyaltyEvent-api-response-object.yaml#/components/schemas/loyaltyEventResponseObject'
        "404":
          description: "NOT FOUND - loyalty Event could not be found"
          content:
            application/json:
              schema:
                $ref: '../../common/swagger-common-api-error-response-object.yaml#/components/schemas/commonApiErrorResponseObject'