openapi: "3.0.3"
info:
  title: "Keran Fidelity System - add API"
  description: "This API is used to add loyalty Events to the database"
  version: "1.0.0"
servers:
  - url: "https://keran_fidelity_system_service/api/v1"
paths:
  /api/v1/loyaltyEvent:
    post:
      tags:
        - LoyaltyEventAddController
      summary: "Add loyalty Event."
      operationId: "addLoyaltyEventById"
      description: "Adds a specific loyalty Event to the database"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../model/swagger-loyaltyEvent.yaml#/components/schemas/loyaltyEventApiObject'
      responses:
        "200":
          description: "OK - loyalty Event created successfully"
          content:
            application/json:
              schema:
                $ref: '../model/swagger-loyaltyEvent-api-response-object.yaml#/components/schemas/loyaltyEventResponseObject'
        "404":
          description: "NOT FOUND - loyalty customer could not be found"
          content:
            application/json:
              schema:
                $ref: '../../common/swagger-common-api-error-response-object.yaml#/components/schemas/commonApiErrorResponseObject'