components:
  schemas:
    loyaltyCustomerApiObject:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        customerNumber:
          type: "string"
        registrationDate:
          type: "string"
          format: "date"
        lastModificationOn:
          type: "string"
          format: "date"
        lastModificationBy:
          type: "string"
