openapi: "3.0.3"
info:
  title: "Keran Fidelity System - Person delete API"
  description: "This API is used to remove persons from the database"
  version: "1.0.0"
servers:
  - url: "https://keran_fidelity_system_service/api/v1"
paths:
  /api/v1/person/{personId}:
    delete:
      tags:
        - personDeleteController
      summary: "Delete person by ID."
      operationId: "deletePersonById"
      description: "Deletes a specific person by its database ID"
      parameters:
        - name: "personId"
          in: "path"
          description: "Existing database ID of a person"
          required: true
          schema:
            type: "string"
            format: "uuid"
            example: "8d2f54d8-6ee7-4e20-854d-7fccc9b477b4"
      responses:
        "200":
          description: "OK - person deleted successfully"
          content:
            application/json:
              schema:
                $ref: '../model/swagger-person-api-response-object.yaml#/components/schemas/personResponseObject'
        "404":
          description: "NOT FOUND - person could not be found"
          content:
            application/json:
              schema:
                $ref: '../../common/swagger-common-api-error-response-object.yaml#/components/schemas/commonApiErrorResponseObject'