components:
  schemas:
    loyaltyProgramResponseObject:
      type: "object"
      properties:
        common:
          $ref: "../../common/swagger-common.yaml#/components/schemas/common"
        loyaltyAccountApiObjects:
          type: "array"
          items:
            $ref: "swagger-loyaltyProgram.yaml#/components/schemas/loyaltyProgramApiObject"