components:
  schemas:
    loyaltyProgramApiObject:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        name:
          type: "string"
        description:
          type: "string"
        startDate:
          type: "string"
          format: "date"
        endDate:
          type: "string"
          format: "date"
          required: false
        imageUrl:
          type: "string"
        lastModificationOn:
          type: "string"
          format: "date"
        lastModificationBy:
          type: "string"
