components:
  schemas:
    loyaltyPointBalanceApiObject:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        loyaltyAccountId:
          type: "string"
          format: "uuid"
        loyaltyPointId:
          type: "string"
          format: "uuid"
        balance:
          type: "int"
        lastModificationOn:
          type: "string"
          format: "date"
        lastModificationBy:
          type: "string"
