components:
  schemas:
    loyaltyPointBalanceResponseObject:
      type: "object"
      properties:
        common:
          $ref: "../../common/swagger-common.yaml#/components/schemas/common"
        loyaltyPointBalanceApiObjects:
          type: "array"
          items:
            $ref: "swagger-loyaltyPointBalance.yaml#/components/schemas/loyaltyPointBalanceApiObject"