openapi: "3.0.3"
info:
  title: "Keran Fidelity System - Loyalty Account update API"
  description: "This API is used to update loyalty accounts"
  version: "1.0.0"
servers:
  - url: "https://keran_fidelity_system_service/api/v1"
paths:
  /api/v1/loyaltyAccount/{loyaltyAccountId}:
    put:
      tags:
        - LoyaltyAccountUpdateController
      summary: "Update loyalty account."
      operationId: "updateLoyaltyAccount"
      description: "Updates a specific loyalty Account"
      parameters:
        - name: "loyaltyAccountId"
          in: "path"
          description: "Existing database ID of a loyalty account"
          required: true
          schema:
            type: "string"
            format: "uuid"
            example: "8d2f54d8-6ee7-4e20-854d-7fccc9b477b4"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../model/swagger-loyaltyAccount.yaml#/components/schemas/loyaltyAccountApiObject'
      responses:
        "200":
          description: "OK - loyalty account created successfully"
          content:
            application/json:
              schema:
                $ref: '../model/swagger-loyaltyAccount-api-response-object.yaml#/components/schemas/loyaltyAccountResponseObject'
        "404":
          description: "NOT FOUND - loyalty customer could not be found"
          content:
            application/json:
              schema:
                $ref: '../../common/swagger-common-api-error-response-object.yaml#/components/schemas/commonApiErrorResponseObject'