openapi: "3.0.3"
info:
  title: "Keran Fidelity System - add API"
  description: "This API is used to add loyalty programs to the database"
  version: "1.0.0"
servers:
  - url: "https://keran_fidelity_system_service/api/v1"
paths:
  /api/v1/loyaltyProgram:
    post:
      tags:
        - LoyaltyProgramAddController
      summary: "Add loyalty program."
      operationId: "addLoyaltyProgramById"
      description: "Adds a specific loyalty Program to the database"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../model/swagger-loyaltyProgram.yaml#/components/schemas/loyaltyProgramApiObject'
      responses:
        "200":
          description: "OK - loyalty Program created successfully"
          content:
            application/json:
              schema:
                $ref: '../model/swagger-loyaltyProgram-api-response-object.yaml#/components/schemas/loyaltyProgramResponseObject'
        "404":
          description: "NOT FOUND - loyalty customer could not be found"
          content:
            application/json:
              schema:
                $ref: '../../common/swagger-common-api-error-response-object.yaml#/components/schemas/commonApiErrorResponseObject'