openapi: "3.0.3"
info:
  title: "Keran Fidelity System - Loyalty Program update API"
  description: "This API is used to update loyalty Programs"
  version: "1.0.0"
servers:
  - url: "https://keran_fidelity_system_service/api/v1"
paths:
  /api/v1/loyaltyProgram/{loyaltyProgramId}:
    put:
      tags:
        - LoyaltyProgramUpdateController
      summary: "Update loyalty Program."
      operationId: "updateLoyaltyProgram"
      description: "Updates a specific loyalty Program"
      parameters:
        - name: "loyaltyProgramId"
          in: "path"
          description: "Existing database ID of a loyalty Program"
          required: true
          schema:
            type: "string"
            format: "uuid"
            example: "8d2f54d8-6ee7-4e20-854d-7fccc9b477b4"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../model/swagger-loyaltyProgram.yaml#/components/schemas/loyaltyProgramApiObject'
      responses:
        "200":
          description: "OK - loyalty Program created successfully"
          content:
            application/json:
              schema:
                $ref: '../model/swagger-loyaltyProgram-api-response-object.yaml#/components/schemas/loyaltyProgramResponseObject'
        "404":
          description: "NOT FOUND - loyalty customer could not be found"
          content:
            application/json:
              schema:
                $ref: '../../common/swagger-common-api-error-response-object.yaml#/components/schemas/commonApiErrorResponseObject'