openapi: "3.0.3"
info:
  title: "Keran Fidelity System - Loyalty Program find API"
  description: "This API is used to find loyalty Programs from the database"
  version: "1.0.0"
servers:
  - url: "https://keran_fidelity_system_service/api/v1"
paths:
  /api/v1/loyaltyProgram/{loyaltyProgramId}:
    get:
      tags:
        - LoyaltyProgramFindController
      summary: "Find loyalty Program by ID."
      operationId: "findLoyaltyProgramById"
      description: "Finds a specific loyalty Program by its database ID"
      parameters:
        - name: "loyaltyProgramId"
          in: "path"
          description: "Existing database ID of a loyalty Program"
          required: true
          schema:
            type: "string"
            format: "uuid"
            example: "8d2f54d8-6ee7-4e20-854d-7fccc9b477b4"
      responses:
        "200":
          description: "OK - loyalty Program found successfully"
          content:
            application/json:
              schema:
                $ref: '../model/swagger-loyaltyProgram-api-response-object.yaml#/components/schemas/loyaltyProgramResponseObject'
        "404":
          description: "NOT FOUND - loyalty Program could not be found"
          content:
            application/json:
              schema:
                $ref: '../../common/swagger-common-api-error-response-object.yaml#/components/schemas/commonApiErrorResponseObject'