openapi: "3.0.3"
info:
  title: "Keran Fidelity System - delete API"
  description: "This API is used to remove loyalty EventConfigurations from the database"
  version: "1.0.0"
servers:
  - url: "https://keran_fidelity_system_service/api/v1"
paths:
  /api/v1/loyaltyEventConfiguration/{loyaltyEventConfigurationId}:
    delete:
      tags:
        - loyaltyEventConfigurationDeleteController
      summary: "Delete loyalty EventConfiguration by ID."
      operationId: "deleteLoyaltyEventConfigurationById"
      description: "Deletes a specific loyalty EventConfiguration by its database ID"
      parameters:
        - name: "loyaltyEventConfigurationId"
          in: "path"
          description: "Existing database ID of a loyalty EventConfiguration"
          required: true
          schema:
            type: "string"
            format: "uuid"
            example: "8d2f54d8-6ee7-4e20-854d-7fccc9b477b4"
      responses:
        "200":
          description: "OK - loyalty EventConfiguration deleted successfully"
          content:
            application/json:
              schema:
                $ref: '../model/swagger-loyaltyEventConfiguration-api-response-object.yaml#/components/schemas/loyaltyEventConfigurationResponseObject'
        "404":
          description: "NOT FOUND - loyalty EventConfiguration could not be found"
          content:
            application/json:
              schema:
                $ref: '../../common/swagger-common-api-error-response-object.yaml#/components/schemas/commonApiErrorResponseObject'