components:
  schemas:
    loyaltyEventResponseObject:
      type: "object"
      properties:
        common:
          $ref: "../../common/swagger-common.yaml#/components/schemas/common"
        loyaltyEventApiObjects:
          type: "array"
          items:
            $ref: "swagger-loyaltyEvent.yaml#/components/schemas/loyaltyEventApiObject"