components:
  schemas:
    loyaltyAccountApiObject:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        loyaltyCustomerId:
          type: "string"
          format: "uuid"
        loyaltyProgramId:
          type: "string"
          format: "uuid"
        loyaltyAccountType:
          type: "string"
          enum:
            - "L1_STANDARD"
            - "L2_PREMIUM"
            - "L3_VIP"
        accountNumber:
          type: "string"
        externalAccountNumber:
          type: "string"
          required: false
        startDate:
          type: "string"
          format: "date"
        closeDate:
          type: "string"
          format: "date"
          required: false
        lastModificationOn:
          type: "string"
          format: "date"
        lastModificationBy:
          type: "string"
