openapi: "3.0.3"
info:
  title: "Keran Fidelity System - Loyalty Customer add API"
  description: "This API is used to add loyalty Customers to the database"
  version: "1.0.0"
servers:
  - url: "https://keran_fidelity_system_service/api/v1"
paths:
  /loyaltyCustomer:
    post:
      tags:
        - LoyaltyCustomerAddController
      summary: "Add loyalty Customer."
      operationId: "addLoyaltyCustomerById"
      description: "Adds a specific loyalty Customer to the database"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../model/swagger-loyaltyCustomer.yaml#/components/schemas/loyaltyCustomerApiObject'
      responses:
        "200":
          description: "OK - loyalty Customer created successfully"
          content:
            application/json:
              schema:
                $ref: '../model/swagger-loyaltyCustomer-api-response-object.yaml#/components/schemas/loyaltyCustomerResponseObject'
        "400":
          description: "BAD REQUEST - loyalty Customer was not created"
          content:
            application/json:
              schema:
                $ref: '../../common/swagger-common-api-error-response-object.yaml#/components/schemas/commonApiErrorResponseObject'