openapi: "3.0.3"
info:
  title: "Keran Fidelity System - Loyalty Customer update API"
  description: "This API is used to update loyalty Customers"
  version: "1.0.0"
servers:
  - url: "https://keran_fidelity_system_service/api/v1"
paths:
  /api/v1/loyaltyCustomer/{loyaltyCustomerId}:
    put:
      tags:
        - LoyaltyCustomerUpdateController
      summary: "Update loyalty Customer."
      operationId: "updateLoyaltyCustomer"
      description: "Updates a specific loyalty Customer"
      parameters:
        - name: "loyaltyCustomerId"
          in: "path"
          description: "Existing database ID of a loyalty Customer"
          required: true
          schema:
            type: "string"
            format: "uuid"
            example: "8d2f54d8-6ee7-4e20-854d-7fccc9b477b4"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../model/swagger-loyaltyCustomer.yaml#/components/schemas/loyaltyCustomerApiObject'
      responses:
        "200":
          description: "OK - loyalty Customer created successfully"
          content:
            application/json:
              schema:
                $ref: '../model/swagger-loyaltyCustomer-api-response-object.yaml#/components/schemas/loyaltyCustomerResponseObject'
        "404":
          description: "NOT FOUND - loyalty customer could not be found"
          content:
            application/json:
              schema:
                $ref: '../../common/swagger-common-api-error-response-object.yaml#/components/schemas/commonApiErrorResponseObject'