components:
  schemas:
    loyaltyEventOccurrenceResponseObject:
      type: "object"
      properties:
        common:
          $ref: "../../common/swagger-common.yaml#/components/schemas/common"
        loyaltyEventOccurrenceApiObjects:
          type: "array"
          items:
            $ref: "swagger-loyaltyEventOccurrence.yaml#/components/schemas/loyaltyEventOccurrenceApiObject"