components:
  schemas:
    loyaltyEventOccurrenceApiObject:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        loyaltyCustomerId:
          type: "string"
          format: "uuid"
        loyaltyEventId:
          type: "string"
          format: "uuid"
        dateOfOccurrence:
          type: "string"
          format: "date"
        quantityOfOccurrence:
          type: "int"
        source:
          type: "string"
        lastModificationOn:
          type: "string"
          format: "date"
        lastModificationBy:
          type: "string"
