openapi: "3.0.3"
info:
  title: "Keran Hexagonal Demo - someName API"
  description: "This API is used to remove someNames from the database"
  version: "1.0.0"
servers:
  - url: "https://keran_hexagonal_demo_service/api/v1"
paths:
  /someName/{someNameId}:
    delete:
      tags:
        - someNameDeleteController
      summary: "Delete someName by ID."
      operationId: "deleteSomeNameById"
      description: "Deletes a specific someName by its database ID"
      parameters:
        - name: "someNameId"
          in: "path"
          description: "Existing database ID of a someName"
          required: true
          schema:
            type: "string"
            format: "uuid"
            example: "{1232312-123123123-123213213-123123123}"
      responses:
        "200":
          description: "OK - someName deleted successfully"
          content:
            application/json:
              schema:
                $ref: '../model/swagger-someName-api-response-object.yaml#/components/schemas/someNameResponseObject'
        "404":
          description: "NOT FOUND - someName could not be found"
          content:
            application/json:
              schema:
                $ref: '../model/swagger-someName-api-response-object.yaml#/components/schemas/someNameResponseObject'