components:
  schemas:
    someNameApiObject:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        # new fields go here:

        lastModificationOn:
          type: "string"
          format: "date"
        lastModificationBy:
          type: "string"
