components:
  schemas:
    personApiObject:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        loyaltyCustomerId:
          type: "string"
          format: "uuid"
        salutation:
          type: "string"
        firstName:
          type: "string"
        middleName:
          type: "string"
        firstLastName:
          type: "string"
        secondLastName:
          type: "string"
        dateOfBirth:
          type: "string"
          format: "date"
        lastModificationOn:
          type: "string"
          format: "date"
        lastModificationBy:
          type: "string"
