components:
  schemas:
    personResponseObject:
      type: "object"
      properties:
        common:
          $ref: "../../common/swagger-common.yaml#/components/schemas/common"
        personApiObjects:
          type: "array"
          items:
            $ref: "swagger-person.yaml#/components/schemas/personApiObject"